### ISSUE TITLE
Tails?

### ISSUE THREAD

**Issue by LuminaDragon** [kayila/elisium18#4]
http://minecraftsix.com/tails-mod/

**Comment by kayila** [comment]
Don't trust minecraftsix.com, they routinely will say mods work for versions that they definitely don't work with. (They will say I mod that was only developed for 1.4.2 will work on 1.8.9)

However..... http://minecraft.curseforge.com/projects/tails

**Comment by kayila** [comment]
Added in 4a43cc3d700d2408a173f5ef8138723c8589af39
